// AUTO-GENERATED by scripts/gen-rules-index.mjs — do not edit by hand.
// Add a new rule by dropping a file in this directory; the barrel regenerates on dev/build.
import type { Rule } from "@/lib/rules/types";
import r_a11y_form_labels from "./a11y-form-labels";
import r_a11y_html_lang from "./a11y-html-lang";
import r_a11y_image_alt from "./a11y-image-alt";
import r_code_console_errors from "./code-console-errors";
import r_code_deprecated_tags from "./code-deprecated-tags";
import r_code_doctype from "./code-doctype";
import r_code_inline_event_handlers from "./code-inline-event-handlers";
import r_code_inline_styles from "./code-inline-styles";
import r_content_h1_count from "./content-h1-count";
import r_content_heading_hierarchy from "./content-heading-hierarchy";
import r_content_lorem_ipsum from "./content-lorem-ipsum";
import r_forms_required_attributes from "./forms-required-attributes";
import r_mobile_viewport_meta from "./mobile-viewport-meta";
import r_nav_bad_links from "./nav-bad-links";
import r_perf_scripts_async_defer from "./perf-scripts-async-defer";
import r_security_mixed_content from "./security-mixed-content";
import r_seo_canonical_present from "./seo-canonical-present";
import r_seo_favicon from "./seo-favicon";
import r_seo_meta_description_exists from "./seo-meta-description-exists";
import r_seo_meta_description_length from "./seo-meta-description-length";
import r_seo_og_tags from "./seo-og-tags";
import r_seo_robots_indexable from "./seo-robots-indexable";
import r_seo_title_exists from "./seo-title-exists";
import r_seo_title_length from "./seo-title-length";
import r_seo_title_unique from "./seo-title-unique";
import r_seo_twitter_card from "./seo-twitter-card";
import r_track_analytics_present from "./track-analytics-present";

export const ALL_RULES: Rule[] = [r_a11y_form_labels, r_a11y_html_lang, r_a11y_image_alt, r_code_console_errors, r_code_deprecated_tags, r_code_doctype, r_code_inline_event_handlers, r_code_inline_styles, r_content_h1_count, r_content_heading_hierarchy, r_content_lorem_ipsum, r_forms_required_attributes, r_mobile_viewport_meta, r_nav_bad_links, r_perf_scripts_async_defer, r_security_mixed_content, r_seo_canonical_present, r_seo_favicon, r_seo_meta_description_exists, r_seo_meta_description_length, r_seo_og_tags, r_seo_robots_indexable, r_seo_title_exists, r_seo_title_length, r_seo_title_unique, r_seo_twitter_card, r_track_analytics_present];
