// AUTO-GENERATED by scripts/gen-catalog.mjs from design/prototype-source.html — do not edit.
// Full QC catalog ported from the design contract; long-tail entries are
// registered as not-implemented CheckDefinitions (shown N/A until a real rule ships).
export type CatalogCheck = {
  id: string;
  category: string;
  name: string;
  checkClass: "critical" | "warning" | "opportunity" | "notice";
  failSeverity: "critical" | "high" | "medium" | "low";
};

export const CATALOG_CHECKS: CatalogCheck[] = [
  {
    "id": "cat-canonical-is-missing",
    "category": "Indexability & Crawl",
    "name": "Canonical is missing",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-noindex-in-html-and-http-header",
    "category": "Indexability & Crawl",
    "name": "Noindex in HTML and HTTP header",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-nofollow-in-html-and-http-header",
    "category": "Indexability & Crawl",
    "name": "Nofollow in HTML and HTTP header",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-h2-has-other-tags-inside",
    "category": "Indexability & Crawl",
    "name": "H2 has other tags inside",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-h1-has-other-tags-inside",
    "category": "Indexability & Crawl",
    "name": "H1 has other tags inside",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-meta-nofollow-pages",
    "category": "Indexability & Crawl",
    "name": "Meta nofollow pages",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-meta-noindex-pages",
    "category": "Indexability & Crawl",
    "name": "Meta noindex pages",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-canonical-to-non-200",
    "category": "Indexability & Crawl",
    "name": "Canonical to non-200",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonical-is-empty",
    "category": "Indexability & Crawl",
    "name": "Canonical is empty",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonical-from-http-to-https",
    "category": "Indexability & Crawl",
    "name": "Canonical from HTTP to HTTPS",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonical-from-https-to-http",
    "category": "Indexability & Crawl",
    "name": "Canonical from HTTPS to HTTP",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-double-slash-in-url",
    "category": "Indexability & Crawl",
    "name": "Double slash in URL",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-mismatched-canonical-tag-in-html-and-http-header",
    "category": "Indexability & Crawl",
    "name": "Mismatched canonical tag in HTML and HTTP header",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-noscript-in-head-contains-invalid-html-elements",
    "category": "Indexability & Crawl",
    "name": "Noscript in head contains invalid HTML elements",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonical-outside-of-head",
    "category": "Indexability & Crawl",
    "name": "Canonical outside of head",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonical-points-to-a-disallowed-url",
    "category": "Indexability & Crawl",
    "name": "Canonical points to a disallowed URL",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonical-points-to-a-noindex-url",
    "category": "Indexability & Crawl",
    "name": "Canonical points to a noindex URL",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonical-points-to-another-canonicalized-url",
    "category": "Indexability & Crawl",
    "name": "Canonical points to another canonicalized URL",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonicalized-url-is-noindex-nofollow",
    "category": "Indexability & Crawl",
    "name": "Canonicalized URL is noindex, nofollow",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-more-than-one-body-tag-on-page",
    "category": "Indexability & Crawl",
    "name": "More than one <body> tag on page",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-more-than-one-body-tag-on-page-x",
    "category": "Indexability & Crawl",
    "name": "More than one </body> tag on page",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-more-than-one-head-tag-on-page",
    "category": "Indexability & Crawl",
    "name": "More than one </head> tag on page",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-more-than-one-html-tag-on-page",
    "category": "Indexability & Crawl",
    "name": "More than one </html> tag on page",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-more-than-one-head-tag-on-page-x",
    "category": "Indexability & Crawl",
    "name": "More than one <head> tag on page",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-more-than-one-html-tag-on-page-x",
    "category": "Indexability & Crawl",
    "name": "More than one <html> tag on page",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-content-after-html",
    "category": "Indexability & Crawl",
    "name": "Page has content after </html>",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-body-tag-is-missing",
    "category": "Indexability & Crawl",
    "name": "</body> tag is missing",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-head-tag-is-missing",
    "category": "Indexability & Crawl",
    "name": "</head> tag is missing",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-html-tag-is-missing",
    "category": "Indexability & Crawl",
    "name": "</html> tag is missing",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-head-tag-is-missing-x",
    "category": "Indexability & Crawl",
    "name": "<head> tag is missing",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-body-tag-is-missing-x",
    "category": "Indexability & Crawl",
    "name": "<body> tag is missing",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-html-tag-is-missing-x",
    "category": "Indexability & Crawl",
    "name": "<html> tag is missing",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-disallowed-css-files",
    "category": "Indexability & Crawl",
    "name": "Page has disallowed CSS files",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-disallowed-images",
    "category": "Indexability & Crawl",
    "name": "Page has disallowed images",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-disallowed-javascript-files",
    "category": "Indexability & Crawl",
    "name": "Page has disallowed JavaScript files",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-no-declared-character-encoding",
    "category": "Indexability & Crawl",
    "name": "Page has no declared character encoding",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-mismatched-nofollow-directives-in-html-and-header",
    "category": "Indexability & Crawl",
    "name": "Mismatched nofollow directives in HTML and header",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-mismatched-noindex-directives-in-html-and-header",
    "category": "Indexability & Crawl",
    "name": "Mismatched noindex directives in HTML and header",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-content-before-doctype-html",
    "category": "Indexability & Crawl",
    "name": "Page has content before <!doctype html>",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonical-is-a-relative-url",
    "category": "Indexability & Crawl",
    "name": "Canonical is a relative URL",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-meta-robots-found-outside-of-head",
    "category": "Indexability & Crawl",
    "name": "Meta robots found outside of <head>",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-multiple-base-urls",
    "category": "Indexability & Crawl",
    "name": "Multiple base URLs",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-multiple-canonical-tags",
    "category": "Indexability & Crawl",
    "name": "Multiple canonical tags",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-multiple-noindex-directives",
    "category": "Indexability & Crawl",
    "name": "Multiple noindex directives",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-multiple-mismatched-base-urls",
    "category": "Indexability & Crawl",
    "name": "Multiple, mismatched base URLs",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-base-url-malformed-or-empty",
    "category": "Indexability & Crawl",
    "name": "Base URL malformed or empty",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-canonical-url",
    "category": "Indexability & Crawl",
    "name": "Canonical ≠ URL",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-disallowed-by-robots-txt",
    "category": "Indexability & Crawl",
    "name": "Disallowed by robots.txt",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-noindex-follow-page",
    "category": "Indexability & Crawl",
    "name": "Noindex follow page",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-more-than-three-parameters-in-url",
    "category": "Indexability & Crawl",
    "name": "More than three parameters in URL",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-contains-rel-sponsored-attributes",
    "category": "Indexability & Crawl",
    "name": "Page contains rel=sponsored attributes",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-contains-a-form-with-a-get-method",
    "category": "Indexability & Crawl",
    "name": "Page contains a form with a GET method",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-content-type-other-than-text-html",
    "category": "Indexability & Crawl",
    "name": "Page has content-type other than text/html",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-301-redirects",
    "category": "Redirects",
    "name": "301 redirects",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-redirect-chains",
    "category": "Redirects",
    "name": "Redirect chains",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-meta-refresh-redirect",
    "category": "Redirects",
    "name": "Meta refresh redirect",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-internal-redirects-from-case-normalization",
    "category": "Redirects",
    "name": "Internal redirects from case normalization",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-internal-redirects-from-trailing-slash-mismatch",
    "category": "Redirects",
    "name": "Internal redirects from trailing slash mismatch",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-internal-url-redirect-broken",
    "category": "Redirects",
    "name": "Internal URL redirect broken",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-internal-url-redirects-back-to-itself",
    "category": "Redirects",
    "name": "Internal URL redirects back to itself",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-https-to-http-redirect",
    "category": "Redirects",
    "name": "HTTPS to HTTP redirect",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-http-to-https-redirect",
    "category": "Redirects",
    "name": "HTTP to HTTPS redirect",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-3xx-other-redirects",
    "category": "Redirects",
    "name": "3xx other redirects",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-302-redirects",
    "category": "Redirects",
    "name": "302 redirects",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-referenced-for-more-than-one-language-in-hreflang",
    "category": "Localization & Hreflang",
    "name": "Page referenced for more than one language in hreflang",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-mismatched-hreflang-and-html-lang-declarations",
    "category": "Localization & Hreflang",
    "name": "Mismatched hreflang and HTML lang declarations",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-has-conflicting-incoming-hreflang-annotations",
    "category": "Localization & Hreflang",
    "name": "Has conflicting incoming hreflang annotations",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-hreflang-annotation-also-x-default",
    "category": "Localization & Hreflang",
    "name": "Hreflang annotation also x-default",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-missing-hreflang-annotations",
    "category": "Localization & Hreflang",
    "name": "Missing hreflang annotations",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-html-lang-attribute-invalid",
    "category": "Localization & Hreflang",
    "name": "HTML lang attribute invalid",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-hreflang-annotation-invalid",
    "category": "Localization & Hreflang",
    "name": "Hreflang annotation invalid",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-more-than-one-page-for-same-language-in-hreflang",
    "category": "Localization & Hreflang",
    "name": "More than one page for same language in hreflang",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-self-reference-hreflang-annotation-missing",
    "category": "Localization & Hreflang",
    "name": "Self-reference hreflang annotation missing",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-hreflang-to-non-canonical",
    "category": "Localization & Hreflang",
    "name": "Hreflang to non-canonical",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-has-outgoing-hreflang-annotations-using-relative-urls",
    "category": "Localization & Hreflang",
    "name": "Has outgoing hreflang annotations using relative URLs",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-has-outgoing-hreflang-annotations-to-redirecting-urls",
    "category": "Localization & Hreflang",
    "name": "Has outgoing hreflang annotations to redirecting URLs",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-invalid-incoming-hreflang-annotations",
    "category": "Localization & Hreflang",
    "name": "Invalid incoming hreflang annotations",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-noindex-url-has-incoming-hreflang",
    "category": "Localization & Hreflang",
    "name": "Noindex URL has incoming hreflang",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-missing-reciprocal-hreflang-no-return-tag",
    "category": "Localization & Hreflang",
    "name": "Missing reciprocal hreflang (no return-tag)",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-has-outgoing-hreflang-annotations-to-broken-urls",
    "category": "Localization & Hreflang",
    "name": "Has outgoing hreflang annotations to broken URLs",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-has-outgoing-hreflang-annotations-to-disallowed-urls",
    "category": "Localization & Hreflang",
    "name": "Has outgoing hreflang annotations to disallowed URLs",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-has-outgoing-hreflang-annotations-to-noindex-urls",
    "category": "Localization & Hreflang",
    "name": "Has outgoing hreflang annotations to noindex URLs",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonicalized-url-has-incoming-hreflang",
    "category": "Localization & Hreflang",
    "name": "Canonicalized URL has incoming hreflang",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-disallowed-url-has-incoming-hreflang",
    "category": "Localization & Hreflang",
    "name": "Disallowed URL has incoming hreflang",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-hreflang-defined-but-html-lang-missing",
    "category": "Localization & Hreflang",
    "name": "Hreflang defined but HTML lang missing",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-x-default-hreflang-annotation-missing",
    "category": "Localization & Hreflang",
    "name": "X-default hreflang annotation missing",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-not-all-pages-from-hreflang-group-were-crawled",
    "category": "Localization & Hreflang",
    "name": "Not all pages from hreflang group were crawled",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-identical-headings",
    "category": "Duplicate Content",
    "name": "Page has identical headings",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-identical-alt-tags",
    "category": "Duplicate Content",
    "name": "Page has identical alt tags",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-h1-alt",
    "category": "Duplicate Content",
    "name": "H1 = Alt",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-title-duplicates",
    "category": "Duplicate Content",
    "name": "Title duplicates",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonical-loop",
    "category": "Duplicate Content",
    "name": "Canonical loop",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-technically-duplicate-urls",
    "category": "Duplicate Content",
    "name": "Technically duplicate URLs",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonical-points-to-homepage",
    "category": "Duplicate Content",
    "name": "Canonical points to homepage",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-h1-description",
    "category": "Duplicate Content",
    "name": "H1 = Description",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-title-alt",
    "category": "Duplicate Content",
    "name": "Title = Alt",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-h1-title",
    "category": "Duplicate Content",
    "name": "H1 = Title",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-more-than-one-h1-on-page",
    "category": "Duplicate Content",
    "name": "More than one h1 on page",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-canonical-points-to-external-url",
    "category": "Duplicate Content",
    "name": "Canonical points to external URL",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-canonical-tag-in-html-and-http-header",
    "category": "Duplicate Content",
    "name": "Canonical tag in HTML and HTTP header",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-working-protocol-redirect-http-to-https",
    "category": "Duplicate Content",
    "name": "Working protocol redirect: HTTP to HTTPS",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-url-contains-upper-case-characters",
    "category": "Internal Resources",
    "name": "URL contains upper case characters",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-url-contains-more-than-one-google-tag-manager-code",
    "category": "Internal Resources",
    "name": "URL contains more than one Google Tag Manager code",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-url-contains-no-google-tag-manager-code",
    "category": "Internal Resources",
    "name": "URL contains no Google Tag Manager code",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-4xx-client-errors",
    "category": "Internal Resources",
    "name": "4xx client errors",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-5xx-server-errors",
    "category": "Internal Resources",
    "name": "5xx server errors",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-timed-out",
    "category": "Internal Resources",
    "name": "Timed out",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-http-url-contains-a-password-input-field",
    "category": "Internal Resources",
    "name": "HTTP URL contains a password input field",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-has-link-with-a-url-referencing-localhost-or-127-0-0-1",
    "category": "Internal Resources",
    "name": "Has link with a URL referencing LocalHost or 127.0.0.1",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-has-link-with-a-url-referencing-a-local-or-unc-file-path",
    "category": "Internal Resources",
    "name": "Has link with a URL referencing a local or UNC file path",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-url-resolves-under-both-http-and-https",
    "category": "Internal Resources",
    "name": "URL resolves under both HTTP and HTTPS",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-broken-css-files",
    "category": "Internal Resources",
    "name": "Page has broken CSS files",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-broken-images",
    "category": "Internal Resources",
    "name": "Page has broken images",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-broken-javascript-files",
    "category": "Internal Resources",
    "name": "Page has broken JavaScript files",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-has-a-link-with-whitespace-in-href-attribute",
    "category": "Internal Resources",
    "name": "Has a link with whitespace in href attribute",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-empty-src-attributes",
    "category": "Internal Resources",
    "name": "Page has empty src attributes",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-url-contains-repetitive-elements",
    "category": "Internal Resources",
    "name": "URL contains repetitive elements",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-url-contains-non-ascii-characters",
    "category": "Internal Resources",
    "name": "URL contains non-ASCII characters",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-query-string-contains-a-question-mark",
    "category": "Internal Resources",
    "name": "Query string contains a question mark",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-long-urls",
    "category": "Internal Resources",
    "name": "Long URLs",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-query-string-contains-sort-parameters",
    "category": "Internal Resources",
    "name": "Query string contains sort parameters",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-query-string-contains-search-or-filter-parameters",
    "category": "Internal Resources",
    "name": "Query string contains search or filter parameters",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-query-string-contains-repetitive-parameters",
    "category": "Internal Resources",
    "name": "Query string contains repetitive parameters",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-query-string-contains-paginated-parameters",
    "category": "Internal Resources",
    "name": "Query string contains paginated parameters",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-whitespace-in-url",
    "category": "Internal Resources",
    "name": "Whitespace in URL",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-xml-sitemap-is-missing",
    "category": "XML Sitemaps",
    "name": "XML sitemap is missing",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-4xx-client-errors-in-xml-sitemaps",
    "category": "XML Sitemaps",
    "name": "4xx client errors in XML sitemaps",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-5xx-server-errors-in-xml-sitemaps",
    "category": "XML Sitemaps",
    "name": "5xx server errors in XML sitemaps",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonicalized-url-in-xml-sitemaps",
    "category": "XML Sitemaps",
    "name": "Canonicalized URL in XML sitemaps",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-disallowed-url-in-xml-sitemaps",
    "category": "XML Sitemaps",
    "name": "Disallowed URL in XML sitemaps",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-noindex-url-in-xml-sitemaps",
    "category": "XML Sitemaps",
    "name": "Noindex URL in XML sitemaps",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-3xx-redirects-in-xml-sitemaps",
    "category": "XML Sitemaps",
    "name": "3xx redirects in XML sitemaps",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-timed-out-url-in-xml-sitemaps",
    "category": "XML Sitemaps",
    "name": "Timed out URL in XML sitemaps",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-url-in-multiple-xml-sitemaps",
    "category": "XML Sitemaps",
    "name": "URL in multiple XML sitemaps",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-an-anchored-image-with-no-alt-text",
    "category": "Links",
    "name": "Page has an anchored image with no alt text",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-broken-jump-link",
    "category": "Links",
    "name": "Broken jump link",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-no-outgoing-links",
    "category": "Links",
    "name": "Page has no outgoing links",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-outbound-internal-links-with-one-word-anchor",
    "category": "Links",
    "name": "Page has outbound internal links with one word anchor",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-has-an-internal-link-with-no-anchor-text",
    "category": "Links",
    "name": "Has an internal link with no anchor text",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-less-than-10-internal-backlinks",
    "category": "Links",
    "name": "Page has less than 10 internal backlinks",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-more-than-2-links-to-internal-page-with-the-same-anchor",
    "category": "Links",
    "name": "Page has more than 2 links to internal page with the same anchor",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-link-with-a-url-in-onclick-attribute",
    "category": "Links",
    "name": "Page has link with a URL in onclick attribute",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-empty-links",
    "category": "Links",
    "name": "Empty links \"#\"",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-orphan-urls-only-found-via-sitemap",
    "category": "Links",
    "name": "Orphan URLs - only found via sitemap",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-link-to-a-non-http-protocol",
    "category": "Links",
    "name": "Page has link to a non-HTTP protocol",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-outgoing-links-with-malformed-href-data",
    "category": "Links",
    "name": "Page has outgoing links with malformed href data",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-more-than-100-external-links",
    "category": "Links",
    "name": "Page has more than 100 external links",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-url-receives-both-follow-and-nofollow-internal-links",
    "category": "Links",
    "name": "URL receives both follow and nofollow internal links",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-more-than-100-identical-internal-links",
    "category": "Links",
    "name": "Page has more than 100 identical internal links",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-has-a-link-with-an-empty-href-attribute",
    "category": "Links",
    "name": "Has a link with an empty href attribute",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-has-only-one-followed-internal-linking-url",
    "category": "Links",
    "name": "Has only one followed internal linking URL",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-internal-links-to-3xx-pages",
    "category": "Links",
    "name": "Page has internal links to 3xx pages",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-internal-links-to-4xx-pages",
    "category": "Links",
    "name": "Page has internal links to 4xx pages",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-broken-links-to-external-websites",
    "category": "Links",
    "name": "Page has broken links to external websites",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-more-than-100-links-before-h1-tag",
    "category": "Links",
    "name": "Page has more than 100 links before H1 tag",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-internal-backlinks-with-the-same-anchor",
    "category": "Links",
    "name": "Page has internal backlinks with the same anchor",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-incoming-followed-links-that-do-not-use-descriptive-anchor-te",
    "category": "Links",
    "name": "Page has incoming followed links that do not use descriptive anchor text",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-one-or-more-outgoing-followed-links-with-non-descriptive-anch",
    "category": "Links",
    "name": "Page has one or more outgoing followed links with non descriptive anchor text",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-links-in-the-footer-with-a-no-follow-attribute",
    "category": "Links",
    "name": "Links in the footer with a no-follow attribute",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-nofollow-outgoing-internal-links",
    "category": "Links",
    "name": "Page has nofollow outgoing internal links",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-http-page-has-internal-links-to-https",
    "category": "Links",
    "name": "HTTP page has internal links to HTTPS",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-more-than-100-internal-links",
    "category": "Links",
    "name": "Page has more than 100 internal links",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-only-has-nofollow-incoming-internal-links",
    "category": "Links",
    "name": "Page only has nofollow incoming internal links",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-google-tag-manager-code-in-body",
    "category": "Code Validation",
    "name": "Google Tag Manager code in <body>",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-table-but-has-no-caption-attribute",
    "category": "Code Validation",
    "name": "Page has <table> but has no <caption> attribute",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-headings-hierarchy-is-broken",
    "category": "Code Validation",
    "name": "Headings hierarchy is broken",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-tags-with-style-attributes",
    "category": "Code Validation",
    "name": "Page has tags with style attributes",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-html-tag-is-empty",
    "category": "Code Validation",
    "name": "<html> tag is empty",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-has-no-declared-doctype-html",
    "category": "Code Validation",
    "name": "Page has no declared <!doctype html>",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-php-fatal-error",
    "category": "Code Validation",
    "name": "PHP fatal error",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-contains-different-structured-data-formats",
    "category": "Code Validation",
    "name": "Page contains different structured data formats",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-table-but-has-no-th-attribute",
    "category": "Code Validation",
    "name": "Page has <table> but has no <th> attribute",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-identical-html-id-attributes",
    "category": "Code Validation",
    "name": "Page has identical HTML id attributes",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-missing-alt-text",
    "category": "Content Relevance",
    "name": "Missing alt text",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-h1-is-empty",
    "category": "Content Relevance",
    "name": "H1 is empty",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-h2-is-missing",
    "category": "Content Relevance",
    "name": "H2 is missing",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-h1-is-missing",
    "category": "Content Relevance",
    "name": "H1 is missing",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-description-is-empty",
    "category": "Content Relevance",
    "name": "Description is empty",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-html-lang-attribute-missing",
    "category": "Content Relevance",
    "name": "HTML lang attribute missing",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-low-word-count",
    "category": "Content Relevance",
    "name": "Low word count",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-no-strong-importance-elements",
    "category": "Content Relevance",
    "name": "Page has no strong importance elements",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-alt-tags-with-one-word",
    "category": "Content Relevance",
    "name": "Page has alt tags with one word",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-no-list-markdown",
    "category": "Content Relevance",
    "name": "Page has no list markdown",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-paragraphs-are-missing",
    "category": "Content Relevance",
    "name": "Paragraphs are missing",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-text-to-code-ratio-10",
    "category": "Content Relevance",
    "name": "Text to code ratio < 10%",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-description-too-short",
    "category": "Content Relevance",
    "name": "Description too short",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-h1-too-short",
    "category": "Content Relevance",
    "name": "H1 too short",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-description-too-long",
    "category": "Content Relevance",
    "name": "Description too long",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-duplicate-pages-without-canonical",
    "category": "Content Relevance",
    "name": "Duplicate pages without canonical",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-more-than-one-body-tag-on-page-x-x",
    "category": "Content Relevance",
    "name": "More than one body tag on page",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-title-is-empty",
    "category": "Content Relevance",
    "name": "Title is empty",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-title-is-missing",
    "category": "Content Relevance",
    "name": "Title is missing",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-more-than-one-title-tag-on-page",
    "category": "Content Relevance",
    "name": "More than one title tag on page",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-lorem-ipsum-content-on-the-live-site",
    "category": "Content Relevance",
    "name": "Lorem Ipsum content on the live site",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-h1-duplicates",
    "category": "Content Relevance",
    "name": "H1 duplicates",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-description-duplicates",
    "category": "Content Relevance",
    "name": "Description duplicates",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-description-is-missing",
    "category": "Content Relevance",
    "name": "Description is missing",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-more-than-one-description-tag-on-page",
    "category": "Content Relevance",
    "name": "More than one description tag on page",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-https-page-links-to-http-image",
    "category": "Content Relevance",
    "name": "HTTPS page links to HTTP image",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-not-been-updated-more-than-1-year",
    "category": "Content Relevance",
    "name": "Page has not been updated more than 1 year",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-author-box-with-admin",
    "category": "Content Relevance",
    "name": "Author box with \"Admin\"",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-might-have-an-outdated-title",
    "category": "Content Relevance",
    "name": "Page might have an outdated title",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-broken-images-on-page",
    "category": "Content Relevance",
    "name": "Broken images on page",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-code-has-less-than-500-symbols",
    "category": "Content Relevance",
    "name": "Page code has less than 500 symbols",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-non-html-urls",
    "category": "Content Relevance",
    "name": "Non-HTML URLs",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-title-too-long",
    "category": "Content Relevance",
    "name": "Title too long",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-title-too-short",
    "category": "Content Relevance",
    "name": "Title too short",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-h1-too-long",
    "category": "Content Relevance",
    "name": "H1 too long",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-pdf-files-returned-by-crawler",
    "category": "Content Relevance",
    "name": "PDF files returned by crawler",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-description-title",
    "category": "Content Relevance",
    "name": "Description = Title",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-h1-starts-with-a-lowercase-letter",
    "category": "Content Relevance",
    "name": "H1 starts with a lowercase letter",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-h2-starts-with-a-lowercase-letter",
    "category": "Content Relevance",
    "name": "H2 starts with a lowercase letter",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-title-starts-with-a-lowercase-letter",
    "category": "Content Relevance",
    "name": "Title starts with a lowercase letter",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-viewport-meta-tag-is-missing-an-initial-scale",
    "category": "Mobile Friendly",
    "name": "Viewport <meta> tag is missing an initial-scale",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-viewport-meta-tag-has-a-maximum-scale-set",
    "category": "Mobile Friendly",
    "name": "Viewport <meta> tag has a maximum-scale set",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-viewport-meta-tag-prevents-the-user-from-scaling",
    "category": "Mobile Friendly",
    "name": "Viewport <meta> tag prevents the user from scaling",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-has-one-or-more-image-map-map-tags",
    "category": "Mobile Friendly",
    "name": "Has one or more image-map <map> tags",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-missing-viewport-meta-tag-in-head",
    "category": "Mobile Friendly",
    "name": "Missing <viewport> meta tag in <head>",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-multiple-viewport-meta-tags-were-found-in-head",
    "category": "Mobile Friendly",
    "name": "Multiple viewport <meta> tags were found in <head>",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-unsupported-browser-plugins-found",
    "category": "Mobile Friendly",
    "name": "Unsupported browser plugins found",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-viewport-meta-tag-does-not-have-a-width-set",
    "category": "Mobile Friendly",
    "name": "Viewport <meta> tag does not have a width set",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-viewport-meta-tag-has-a-minimum-scale-set",
    "category": "Mobile Friendly",
    "name": "Viewport <meta> tag has a minimum-scale set",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-viewport-meta-tag-has-a-specific-width-set",
    "category": "Mobile Friendly",
    "name": "Viewport <meta> tag has a specific width set",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-viewport-meta-tag-initial-scale-is-incorrect",
    "category": "Mobile Friendly",
    "name": "Viewport <meta> tag initial-scale is incorrect",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-touch-icons-declared-for-all-platforms",
    "category": "Mobile Friendly",
    "name": "Touch icons declared for all platforms",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-add-dimensions-to-images",
    "category": "Page Speed & Performance",
    "name": "Add dimensions to images",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-defer-offscreen-images",
    "category": "Page Speed & Performance",
    "name": "Defer offscreen images",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-serve-images-in-next-gen-formats",
    "category": "Page Speed & Performance",
    "name": "Serve images in next gen formats",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-comments-in-code-has-more-than-1000-symbols",
    "category": "Page Speed & Performance",
    "name": "Comments in code has more than 1000 symbols",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-size-is-over-4-mb",
    "category": "Page Speed & Performance",
    "name": "Page size is over 4 MB",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-serve-static-assets-with-an-efficient-cache-policy",
    "category": "Page Speed & Performance",
    "name": "Serve static assets with an efficient cache policy",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-image-size-is-over-100-kb",
    "category": "Page Speed & Performance",
    "name": "Image size is over 100 KB",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-css-file-size-is-over-15-kb",
    "category": "Page Speed & Performance",
    "name": "CSS file size is over 15 KB",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-javascript-file-size-is-over-25-kb",
    "category": "Page Speed & Performance",
    "name": "JavaScript file size is over 25 KB",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-size-is-over-2-mb",
    "category": "Page Speed & Performance",
    "name": "Page size is over 2 MB",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-avoid-excessive-dom-size",
    "category": "Page Speed & Performance",
    "name": "Avoid excessive DOM size",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-avoid-excessive-dom-depth",
    "category": "Page Speed & Performance",
    "name": "Avoid excessive DOM depth",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-avoid-excessive-dom-width",
    "category": "Page Speed & Performance",
    "name": "Avoid excessive DOM width",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-use-video-formats-for-animated-content",
    "category": "Page Speed & Performance",
    "name": "Use video formats for animated content",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-web-fonts-are-preloaded",
    "category": "Page Speed & Performance",
    "name": "Web fonts are preloaded",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-http-link-to-www-w3-org",
    "category": "Security",
    "name": "Page has HTTP link to www.w3.org",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-https-page-has-internal-links-to-http",
    "category": "Security",
    "name": "HTTPS page has internal links to HTTP",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-http-urls",
    "category": "Security",
    "name": "HTTP URLs",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-https-url-contains-a-form-posting-to-http",
    "category": "Security",
    "name": "HTTPS URL contains a form posting to HTTP",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-https-page-links-to-http-css",
    "category": "Security",
    "name": "HTTPS page links to HTTP CSS",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-https-page-links-to-http-javascript",
    "category": "Security",
    "name": "HTTPS page links to HTTP JavaScript",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-http-link-to-ogp-me",
    "category": "Security",
    "name": "Page has HTTP link to ogp.me",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-has-http-link-to-schema-org",
    "category": "Security",
    "name": "Page has HTTP link to schema.org",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-page-requires-captcha-authentication-method",
    "category": "Security",
    "name": "Page requires CAPTCHA authentication method",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-no-cookies-are-sent-by-the-website",
    "category": "Security",
    "name": "No cookies are sent by the website",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-open-graph-tags-missing",
    "category": "Social Media",
    "name": "Open Graph tags missing",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-twitter-card-missing",
    "category": "Social Media",
    "name": "Twitter card missing",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-open-graph-tags-incomplete",
    "category": "Social Media",
    "name": "Open Graph tags incomplete",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-open-graph-url-not-matching-canonical",
    "category": "Social Media",
    "name": "Open Graph URL not matching canonical",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-twitter-card-incomplete",
    "category": "Social Media",
    "name": "Twitter card incomplete",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-0-impressions",
    "category": "Search Traffic",
    "name": "Page has 0 impressions",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-non-indexable-page-that-has-at-least-1-impression",
    "category": "Search Traffic",
    "name": "Non-indexable page that has at least 1 impression",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-is-blocked-by-robots-txt-and-has-at-least-1-impression",
    "category": "Search Traffic",
    "name": "Page is blocked by robots.txt and has at least 1 impression",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-4xx-pages-that-have-at-least-1-click",
    "category": "Search Traffic",
    "name": "4xx pages that have at least 1 click",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-canonicalized-pages-that-have-at-least-1-click",
    "category": "Search Traffic",
    "name": "Canonicalized pages that have at least 1 click",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-3xx-pages-that-have-at-least-1-click",
    "category": "Search Traffic",
    "name": "3xx pages that have at least 1 click",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-page-is-not-submitted-to-sitemap-and-has-at-least-1-impression",
    "category": "Search Traffic",
    "name": "Page is not submitted to sitemap and has at least 1 impression",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-has-at-least-1-click",
    "category": "Search Traffic",
    "name": "Page has at least 1 click",
    "checkClass": "opportunity",
    "failSeverity": "low"
  },
  {
    "id": "cat-orphan-pages-with-impressions",
    "category": "Search Traffic",
    "name": "Orphan pages with impressions",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-html-fails-w3c-validation-with-errors",
    "category": "HTML / CSS / JS Validation",
    "name": "HTML fails W3C validation with errors",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-html-has-w3c-validation-warnings",
    "category": "HTML / CSS / JS Validation",
    "name": "HTML has W3C validation warnings",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-css-fails-to-parse-syntax-errors",
    "category": "HTML / CSS / JS Validation",
    "name": "CSS fails to parse (syntax errors)",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-css-contains-invalid-property-values",
    "category": "HTML / CSS / JS Validation",
    "name": "CSS contains invalid property values",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-css-relies-on-vendor-prefix-only-declarations",
    "category": "HTML / CSS / JS Validation",
    "name": "CSS relies on vendor-prefix-only declarations",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-javascript-runtime-errors-in-console",
    "category": "HTML / CSS / JS Validation",
    "name": "JavaScript runtime errors in console",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-javascript-logs-warnings-in-console",
    "category": "HTML / CSS / JS Validation",
    "name": "JavaScript logs warnings in console",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-uncaught-promise-rejections-detected",
    "category": "HTML / CSS / JS Validation",
    "name": "Uncaught promise rejections detected",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-inline-event-handlers-onclick-in-html",
    "category": "HTML / CSS / JS Validation",
    "name": "Inline event handlers (onclick) in HTML",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-document-mixes-html4-xhtml-and-html5-syntax",
    "category": "HTML / CSS / JS Validation",
    "name": "Document mixes HTML4/XHTML and HTML5 syntax",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-css-important-used-excessively",
    "category": "HTML / CSS / JS Validation",
    "name": "CSS !important used excessively",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-unused-css-rules-over-50",
    "category": "HTML / CSS / JS Validation",
    "name": "Unused CSS rules over 50%",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-unminified-css-files",
    "category": "HTML / CSS / JS Validation",
    "name": "Unminified CSS files",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-unminified-javascript-files",
    "category": "HTML / CSS / JS Validation",
    "name": "Unminified JavaScript files",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-duplicate-javascript-libraries-loaded",
    "category": "HTML / CSS / JS Validation",
    "name": "Duplicate JavaScript libraries loaded",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-javascript-library-with-known-vulnerabilities-cve",
    "category": "HTML / CSS / JS Validation",
    "name": "JavaScript library with known vulnerabilities (CVE)",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-deprecated-browser-apis-in-use",
    "category": "Best Practices & Code Review",
    "name": "Deprecated browser APIs in use",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-document-write-used",
    "category": "Best Practices & Code Review",
    "name": "document.write() used",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-synchronous-xhr-on-main-thread",
    "category": "Best Practices & Code Review",
    "name": "Synchronous XHR on main thread",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-mixed-content-active-blocked-by-browser",
    "category": "Best Practices & Code Review",
    "name": "Mixed content (active) blocked by browser",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-missing-rel-noopener-on-target-blank-links",
    "category": "Best Practices & Code Review",
    "name": "Missing rel=\"noopener\" on target=\"_blank\" links",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-permission-geolocation-notification-requested-on-page-load",
    "category": "Best Practices & Code Review",
    "name": "Permission (geolocation/notification) requested on page load",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-console-log-statements-left-in-production",
    "category": "Best Practices & Code Review",
    "name": "console.log statements left in production",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-framework-version-2-majors-behind",
    "category": "Best Practices & Code Review",
    "name": "Framework version 2+ majors behind",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-known-vulnerable-dependency-in-bundle",
    "category": "Best Practices & Code Review",
    "name": "Known-vulnerable dependency in bundle",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-source-maps-exposed-in-production",
    "category": "Best Practices & Code Review",
    "name": "Source maps exposed in production",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-inline-scripts-larger-than-10-kb",
    "category": "Best Practices & Code Review",
    "name": "Inline scripts larger than 10 KB",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-images-served-with-wrong-content-type",
    "category": "Best Practices & Code Review",
    "name": "Images served with wrong Content-Type",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-charset-declared-after-first-1024-bytes",
    "category": "Best Practices & Code Review",
    "name": "Charset declared after first 1024 bytes",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-html-comments-contain-todo-or-fixme",
    "category": "Best Practices & Code Review",
    "name": "HTML comments contain TODO or FIXME",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-scroll-touch-listeners-not-passive",
    "category": "Best Practices & Code Review",
    "name": "Scroll/touch listeners not passive",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-more-than-10-third-party-script-origins",
    "category": "Best Practices & Code Review",
    "name": "More than 10 third-party script origins",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-localstorage-used-for-sensitive-data",
    "category": "Best Practices & Code Review",
    "name": "localStorage used for sensitive data",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-api-keys-or-secrets-visible-in-page-source",
    "category": "Best Practices & Code Review",
    "name": "API keys or secrets visible in page source",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-form-fields-use-native-validation-attributes",
    "category": "Best Practices & Code Review",
    "name": "Form fields use native validation attributes",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-content-security-policy-header-missing",
    "category": "Security Headers & TLS",
    "name": "Content-Security-Policy header missing",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-csp-allows-unsafe-inline",
    "category": "Security Headers & TLS",
    "name": "CSP allows unsafe-inline",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-strict-transport-security-hsts-missing",
    "category": "Security Headers & TLS",
    "name": "Strict-Transport-Security (HSTS) missing",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-x-content-type-options-nosniff-missing",
    "category": "Security Headers & TLS",
    "name": "X-Content-Type-Options: nosniff missing",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-x-frame-options-frame-ancestors-missing",
    "category": "Security Headers & TLS",
    "name": "X-Frame-Options / frame-ancestors missing",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-referrer-policy-header-missing",
    "category": "Security Headers & TLS",
    "name": "Referrer-Policy header missing",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-permissions-policy-header-missing",
    "category": "Security Headers & TLS",
    "name": "Permissions-Policy header missing",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-tls-certificate-expires-within-14-days",
    "category": "Security Headers & TLS",
    "name": "TLS certificate expires within 14 days",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-tls-version-below-1-2-supported",
    "category": "Security Headers & TLS",
    "name": "TLS version below 1.2 supported",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-certificate-chain-incomplete",
    "category": "Security Headers & TLS",
    "name": "Certificate chain incomplete",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-cookies-set-without-secure-flag",
    "category": "Security Headers & TLS",
    "name": "Cookies set without Secure flag",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-cookies-set-without-httponly-flag",
    "category": "Security Headers & TLS",
    "name": "Cookies set without HttpOnly flag",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-cookies-without-samesite-attribute",
    "category": "Security Headers & TLS",
    "name": "Cookies without SameSite attribute",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-server-version-leaked-in-headers-server-x-powered-by",
    "category": "Security Headers & TLS",
    "name": "Server version leaked in headers (Server / X-Powered-By)",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-form-elements-must-have-labels",
    "category": "Accessibility (axe-core)",
    "name": "Form elements must have labels",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-elements-must-meet-minimum-color-contrast-ratio",
    "category": "Accessibility (axe-core)",
    "name": "Elements must meet minimum color contrast ratio",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-focus-indicator-must-be-visible",
    "category": "Accessibility (axe-core)",
    "name": "Focus indicator must be visible",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-aria-attributes-must-be-valid",
    "category": "Accessibility (axe-core)",
    "name": "ARIA attributes must be valid",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-interactive-elements-must-be-keyboard-reachable",
    "category": "Accessibility (axe-core)",
    "name": "Interactive elements must be keyboard reachable",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-must-have-a-main-landmark",
    "category": "Accessibility (axe-core)",
    "name": "Page must have a main landmark",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-heading-order-should-be-semantically-correct",
    "category": "Accessibility (axe-core)",
    "name": "Heading order should be semantically correct",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-touch-targets-must-be-at-least-44-by-44-px",
    "category": "Accessibility (axe-core)",
    "name": "Touch targets must be at least 44 by 44 px",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-page-should-have-a-skip-link",
    "category": "Accessibility (axe-core)",
    "name": "Page should have a skip link",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-video-and-audio-must-have-captions",
    "category": "Accessibility (axe-core)",
    "name": "Video and audio must have captions",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-primary-button-styles-consistent-across-pages",
    "category": "AI Design Review",
    "name": "Primary button styles consistent across pages",
    "checkClass": "critical",
    "failSeverity": "high"
  },
  {
    "id": "cat-footer-structure-consistent-across-pages",
    "category": "AI Design Review",
    "name": "Footer structure consistent across pages",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-header-consistent-across-pages",
    "category": "AI Design Review",
    "name": "Header consistent across pages",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-cta-wording-consistent-across-pages",
    "category": "AI Design Review",
    "name": "CTA wording consistent across pages",
    "checkClass": "warning",
    "failSeverity": "medium"
  },
  {
    "id": "cat-brand-colors-used-consistently",
    "category": "AI Design Review",
    "name": "Brand colors used consistently",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-typography-scale-consistent",
    "category": "AI Design Review",
    "name": "Typography scale consistent",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-spacing-rhythm-consistent",
    "category": "AI Design Review",
    "name": "Spacing rhythm consistent",
    "checkClass": "notice",
    "failSeverity": "low"
  },
  {
    "id": "cat-imagery-style-consistent",
    "category": "AI Design Review",
    "name": "Imagery style consistent",
    "checkClass": "notice",
    "failSeverity": "low"
  }
];
