// Extracts the full CHECKS catalog (19 categories) from the design contract
// (design/prototype-source.html) and generates lib/rules/catalog.gen.ts.
// Long-tail catalog checks ship as CheckDefinitions with implemented=false and
// surface as "not-evaluated" (N/A) in the registry — never as fake passes.
import fs from "node:fs";

const src = fs.readFileSync("design/prototype-source.html", "utf8");
const start = src.indexOf("CHECKS = [");
if (start === -1) throw new Error("CHECKS array not found");
// Find the matching closing bracket of the array literal.
let depth = 0;
let end = -1;
for (let i = src.indexOf("[", start); i < src.length; i++) {
  if (src[i] === "[") depth++;
  else if (src[i] === "]") {
    depth--;
    if (depth === 0) {
      end = i + 1;
      break;
    }
  }
}
const literal = src.slice(src.indexOf("[", start), end);
// The literal is plain JS (single-quoted strings, no functions) — eval in a sandbox-ish way.
const checks = new Function(`return ${literal};`)();

const CLASS = { C: "critical", W: "warning", O: "opportunity", N: "notice" };
const SEVERITY = { C: "high", W: "medium", O: "low", N: "low" };

const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 70);

const rows = [];
const seen = new Set();
for (const [category, list] of checks) {
  for (const item of list) {
    const p = item.indexOf("|");
    const cls = item.slice(0, p);
    const name = item.slice(p + 1);
    let id = `cat-${slug(name)}`;
    while (seen.has(id)) id += "-x";
    seen.add(id);
    rows.push({
      id,
      category,
      name,
      checkClass: CLASS[cls] ?? "notice",
      failSeverity: SEVERITY[cls] ?? "low",
    });
  }
}

const out = [
  "// AUTO-GENERATED by scripts/gen-catalog.mjs from design/prototype-source.html — do not edit.",
  "// Full QC catalog ported from the design contract; long-tail entries are",
  "// registered as not-implemented CheckDefinitions (shown N/A until a real rule ships).",
  "export type CatalogCheck = {",
  "  id: string;",
  "  category: string;",
  "  name: string;",
  '  checkClass: "critical" | "warning" | "opportunity" | "notice";',
  '  failSeverity: "critical" | "high" | "medium" | "low";',
  "};",
  "",
  `export const CATALOG_CHECKS: CatalogCheck[] = ${JSON.stringify(rows, null, 2)};`,
  "",
];
fs.writeFileSync("lib/rules/catalog.gen.ts", out.join("\n"));
console.log(`catalog: ${rows.length} checks across ${checks.length} categories -> lib/rules/catalog.gen.ts`);
